# By default, make an installation called azimuth
fullNameOverride: azimuth

# Configuration for the Argo CD 
argocd:
  # The Argo CD cluster to target
  destination:
    # The URL of the API server
    server: https://kubernetes.default.svc
    # The name of the cluster as known to Argo CD
    # Takes precedence over server if given
    name:
  # The Argo CD project configuration
  project:
    sourceRepos:
      - "*"
    clusterResourceWhitelist:
      - group: "*"
        kind: "*"
    destinations:
      - server: "*"
        namespace: "*"
  # The sync policy to use with Argo apps
  # See https://argo-cd.readthedocs.io/en/stable/user-guide/auto_sync/
  #     https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - "ApplyOutOfSyncOnly=true"
      - "CreateNamespace=true"
      - "ServerSideApply=true"
  # Configuration for the self-managing Argo CD app
  selfManaged:
    # Indicates whether the Argo CD should be self-managing
    enabled: true
    # The location of the kustomize configuration
    repo: https://github.com/stackhpc/azimuth-argo.git
    path: argocd
    version: main
    # Kustomize options for the Argo app
    # See https://argo-cd.readthedocs.io/en/stable/user-guide/kustomize/
    kustomize:
      # Until https://github.com/argoproj/gitops-engine/pull/503 or similar is merged,
      # we need to use our own Argo image
      images:
        - quay.io/argoproj/argocd=ghcr.io/stackhpc/argocd:v2.6.0-stackhpc.2
    kustomizeTemplate: ""

# Values for the raw chart, used to post templated manifests where no chart is available
rawChart:
  repo: https://charts.helm.sh/incubator
  name: raw
  version: 0.2.5

# Configuration for cert-manager
certManager:
  # Indicates if cert-manager should be enabled
  # NOTE: cert-manager is a required dependency of Cluster API
  enabled: true
  chart:
    repo: https://charts.jetstack.io
    name: cert-manager
    version: v1.11.0
  release:
    name: cert-manager
    namespace: cert-manager
    values:
      installCRDs: true
    valuesTemplate: ""
  # Configuration for the HTTP-01 issuer that should be used for HTTPS support
  acmeHttp01Issuer:
    enabled: true
    name: letsencrypt
    server: https://acme-v02.api.letsencrypt.org/directory
    ingressClass: nginx

# Configuration for the Cluster API providers
clusterApi:
  # Indicates if the Cluster API controllers should be enabled
  enabled: true
  # Configuration for the core provider
  core:
    repo: https://github.com/stackhpc/azimuth-argo.git
    path: cluster-api/core
    version: main
    # Kustomize options for the Argo app
    # See https://argo-cd.readthedocs.io/en/stable/user-guide/kustomize/
    kustomize: {}
    kustomizeTemplate: ""
  # Configuration for the bootstrap provider
  bootstrap:
    repo: https://github.com/stackhpc/azimuth-argo.git
    path: cluster-api/bootstrap
    version: main
    # Kustomize options for the Argo app
    # See https://argo-cd.readthedocs.io/en/stable/user-guide/kustomize/
    kustomize: {}
    kustomizeTemplate: ""
  # Configuration for the kubeadm control plane provider
  controlPlane:
    repo: https://github.com/stackhpc/azimuth-argo.git
    path: cluster-api/control-plane
    version: main
    # Kustomize options for the Argo app
    # See https://argo-cd.readthedocs.io/en/stable/user-guide/kustomize/
    kustomize: {}
    kustomizeTemplate: ""
  # Configuation for the openstack infratructure provider
  openstack:
    repo: https://github.com/stackhpc/azimuth-argo.git
    path: cluster-api/openstack
    version: main
    # Kustomize options for the Argo app
    # See https://argo-cd.readthedocs.io/en/stable/user-guide/kustomize/
    kustomize: {}
    kustomizeTemplate: ""
  # Configuration for the StackHPC addon provider
  addons:
    chart:
      repo: https://stackhpc.github.io/cluster-api-addon-provider
      name: cluster-api-addon-provider
      version: 0.1.0-dev.0.feature-argo-support.31
    release:
      name: cluster-api-addon-provider
      namespace: capi-addon-system
      values: {}
      valuesTemplate: ""

# Configuration for Consul
consul:
  # Indicates if Consul should be enabled
  # If not enabled, some components will require external Consul details to be specified
  enabled: true
  chart:
    repo: https://helm.releases.hashicorp.com
    name: consul
    version: 0.49.2
  release:
    name: consul
    namespace: azimuth
    values:
      fullnameOverride: consul
      server:
        replicas: 3
    valuesTemplate: ""
