# The install mode for the installation
installMode: ha

# By default, make an installation called azimuth
fullNameOverride: azimuth

# The Git repository URL to use for kustomize apps
kustomizeGitRepoURL: https://github.com/stackhpc/azimuth-argo.git

# Configuration for the Argo CD 
argocd:
  # The Argo CD cluster to target
  destination:
    # The URL of the API server
    server: https://kubernetes.default.svc
    # The name of the cluster as known to Argo CD
    # Takes precedence over server if given
    name:
  # The Argo CD project configuration
  project:
    sourceRepos:
      - "*"
    clusterResourceWhitelist:
      - group: "*"
        kind: "*"
    destinations:
      - server: "*"
        namespace: "*"
  # The sync policy to use with Argo apps
  # See https://argo-cd.readthedocs.io/en/stable/user-guide/auto_sync/
  #     https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - "CreateNamespace=true"
  # Configuration for the self-managing Argo CD app
  selfManaged:
    # Indicates whether the Argo CD should be self-managing
    enabled: false
    chart:
      repo: https://argoproj.github.io/argo-helm
      name: argo-cd
      version: 5.23.1
    release:
      name: argo-cd
      namespace: # Defaults to the release namespace if not given
      values:
        global:
          # We use a custom image with support for ignoring non-controller references
          # Required until https://github.com/argoproj/gitops-engine/pull/503 (or similar) is merged
          image:
            repository: ghcr.io/stackhpc/argocd
            tag: v2.7.0-stackhpc.3
        configs:
          cm:
            # Use annotations as the tracking method as it allows longer app names
            application.resourceTrackingMethod: annotation
            # Ignore the rules from aggregated roles, used in Cluster API
            resource.compareoptions: |
              ignoreAggregatedRoles: true
            # Allow Argo to assess the health of nested apps in app-of-apps configurations
            resource.customizations.health.argoproj.io_Application: |
              hs = {}
              hs.status = "Progressing"
              hs.message = ""
              if obj.status ~= nil then
                if obj.status.sync ~= nil then
                  if obj.status.sync.status == "Synced" then
                    if obj.status.health ~= nil then
                      hs.status = obj.status.health.status
                      if obj.status.health.message ~= nil then
                        hs.message = obj.status.health.message
                      end
                    end
                  end
                end
              end
              return hs
            # Tell Argo what it means for Cluster API addons to be healthy
            resource.customizations.health.addons.stackhpc.com_HelmRelease: |
              hs = {}
              hs.status = "Progressing"
              hs.message = ""
              if obj.status ~= nil then
                if obj.status.phase == "Ready" then
                  hs.status = "Healthy"
                elseif obj.status.phase == "Suspended" then
                  hs.status = "Suspended"
                elseif obj.status.phase == "Unhealthy" then
                  hs.status = "Degraded"
                  hs.message = obj.status.healthMessage
                elseif obj.status.phase == "Failed" then
                  hs.status = "Degraded"
                  hs.message = obj.status.failureMessage
                elseif obj.status.phase == "Unknown" then
                  hs.status = "Degraded"
                  hs.message = "Status is unknown"
                end
              end
              return hs
            resource.customizations.health.addons.stackhpc.com_Manifests: |
              hs = {}
              hs.status = "Progressing"
              hs.message = ""
              if obj.status ~= nil then
                if obj.status.phase == "Ready" then
                  hs.status = "Healthy"
                elseif obj.status.phase == "Suspended" then
                  hs.status = "Suspended"
                elseif obj.status.phase == "Unhealthy" then
                  hs.status = "Degraded"
                  hs.message = obj.status.healthMessage
                elseif obj.status.phase == "Failed" then
                  hs.status = "Degraded"
                  hs.message = obj.status.failureMessage
                elseif obj.status.phase == "Unknown" then
                  hs.status = "Degraded"
                  hs.message = "Status is unknown"
                end
              end
              return hs
            # Tell Argo what it means for Zenith operator resources to be healthy
            resource.customizations.health.zenith.stackhpc.com_Client: |
              hs = {}
              hs.status = "Progressing"
              hs.message = ""
              if obj.status ~= nil then
                if obj.status.phase == "Available" then
                  hs.status = "Healthy"
                elseif obj.status.phase == "Unavailable" then
                  hs.status = "Degraded"
                elseif obj.status.phase == "Failed" then
                  hs.status = "Degraded"
                elseif obj.status.phase == "Unknown" then
                  hs.status = "Degraded"
                end
              end
              return hs
            resource.customizations.health.zenith.stackhpc.com_Reservation: |
              hs = {}
              hs.status = "Progressing"
              hs.message = ""
              if obj.status ~= nil then
                if obj.status.phase == "Ready" then
                  hs.status = "Healthy"
                elseif obj.status.phase == "Failed" then
                  hs.status = "Degraded"
                elseif obj.status.phase == "Unknown" then
                  hs.status = "Degraded"
                end
              end
              return hs
      valuesTemplate: ""

# Values for the raw chart, used to post templated manifests where no chart is available
rawChart:
  repo: https://charts.helm.sh/incubator
  name: raw
  version: 0.2.5

# Configuration for the wildcard certificate, if used
wildcardCertificate:
  # Indicates if a wildcard certificate should be used
  enabled: false
  # The name of the secret containing the wildcard certificate
  # This will be the same in each namespace in which it is reflected
  secretName: azimuth-tls
  # The namespace to create the "master copy" of the secret in
  secretNamespace: azimuth

# Configuration for ingress
ingress:
  # The base domain for the ingress
  baseDomain: ""
  # Annotations added to all ingresses in the deployment
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: 16k
  # TLS configuration for the ingress
  tls:
    # Indicates whether TLS should be enabled
    enabled: true
  # The subdomains to use for the various components
  subdomains:
    azimuth: portal
    zenithRegistrar: registrar
    harborCore: registry
    harborNotary: notary
    cloudMetricsGrafana: metrics

# Configuration for cert-manager
certManager:
  # Indicates if cert-manager should be enabled
  # NOTE: cert-manager is a required dependency of Cluster API
  enabled: true
  chart:
    repo: https://charts.jetstack.io
    name: cert-manager
    version: v1.11.0
  release:
    name: cert-manager
    namespace: cert-manager
    values:
      installCRDs: true
    valuesTemplate: ""
  # Configuration for the HTTP-01 issuer that should be used for HTTPS support
  acmeHttp01Issuer:
    enabled: true
    name: letsencrypt
    server: https://acme-v02.api.letsencrypt.org/directory
    ingressClass: nginx

# Configuration for the Cluster API providers
clusterApi:
  # Indicates if the Cluster API controllers should be enabled
  enabled: true
  # Configuration for the core provider
  core:
    repo: # Defaults to kustomizeGitRepoURL
    path: kustomize/cluster-api-core
    version: main
    # Kustomize options for the Argo app
    # See https://argo-cd.readthedocs.io/en/stable/user-guide/kustomize/
    kustomize: {}
    kustomizeTemplate: ""
  # Configuration for the bootstrap provider
  bootstrap:
    repo: # Defaults to kustomizeGitRepoURL
    path: kustomize/cluster-api-bootstrap
    version: main
    # Kustomize options for the Argo app
    # See https://argo-cd.readthedocs.io/en/stable/user-guide/kustomize/
    kustomize: {}
    kustomizeTemplate: ""
  # Configuration for the kubeadm control plane provider
  controlPlane:
    repo: # Defaults to kustomizeGitRepoURL
    path: kustomize/cluster-api-control-plane
    version: main
    # Kustomize options for the Argo app
    # See https://argo-cd.readthedocs.io/en/stable/user-guide/kustomize/
    kustomize: {}
    kustomizeTemplate: ""
  # Configuation for the openstack infratructure provider
  openstack:
    repo: # Defaults to kustomizeGitRepoURL
    path: kustomize/cluster-api-openstack
    version: main
    # Kustomize options for the Argo app
    # See https://argo-cd.readthedocs.io/en/stable/user-guide/kustomize/
    kustomize: {}
    kustomizeTemplate: ""
  # Configuration for the StackHPC addon provider
  addons:
    chart:
      repo: https://stackhpc.github.io/cluster-api-addon-provider
      name: cluster-api-addon-provider
      version: 0.1.0-dev.0.feature-argo-support.33
    release:
      name: cluster-api-addon-provider
      namespace: capi-addon-system
      values: {}
      valuesTemplate: ""

# Configuration for AWX
awx:
  # Indicates if AWX should be enabled
  enabled: false

# Configuration for Consul
consul:
  # Indicates if Consul should be enabled
  enabled: true
  chart:
    repo: https://helm.releases.hashicorp.com
    name: consul
    version: 0.49.3
  release:
    name: consul
    namespace: azimuth
    values:
      # Avoid the repeated "consul" in the names by default
      fullnameOverride: consul
    valuesTemplate: ""

# Configuration for Zenith
zenith:
  # Indicates if Zenith should be enabled
  enabled: true
  chart:
    repo: https://stackhpc.github.io/zenith
    name: zenith-server
    version: 0.1.0-dev.0.main.168
  release:
    name: zenith-server
    namespace: azimuth
    defaultsTemplate: |
      common:
        consul:
          address: {{ include "azimuth-argo.consul.host" . | quote }}
        ingress:
          {{- with .Values.ingress.baseDomain }}
          baseDomain: {{ . }}
          {{- end }}
          annotations: {{- toYaml .Values.ingress.annotations | nindent 6 }}
          tls:
            {{- if .Values.ingress.tls.enabled }}
            enabled: true
            {{- if .Values.wildcardCertificate.enabled }}
            secretName: {{ .Values.wildcardCertificate.secretName }}
            {{- else }}
            annotations: {{- include "azimuth-argo.ingress.tls.annotations" . | nindent 8 -}}
            {{- end }}
            {{- else }}
            enabled: false
            {{- end }}
      sync:
        config:
          kubernetes:
            ingress:
              auth:
                url: {{
                  printf
                    "http://%s-api.%s.svc.cluster.local/api/session/verify/"
                    .Values.azimuth.release.name
                    .Values.azimuth.release.namespace
                }}
                {{- if .Values.ingress.baseDomain }}
                signinUrl: {{
                  printf
                    "%s://%s.%s/auth/login"
                    (.Values.ingress.tls.enabled | ternary "https" "http")
                    .Values.ingress.subdomains.azimuth
                    .Values.ingress.baseDomain
                }}
                {{- end }}
      registrar:
        ingress:
          subdomain: {{ .Values.ingress.subdomains.zenithRegistrar }}
        config:
          reservedSubdomains: {{- values .Values.ingress.subdomains | toYaml | nindent 6 }}
    values:
      # We don't need Zenith to deploy a Consul server
      consul:
        enabled: false
      sync:
        config:
          kubernetes:
            ingress:
              auth:
                nextUrlParam: next
                requestHeaders:
                  accept: application/json
                responseHeaders:
                  - X-Remote-User
    valuesTemplate: ""

# Configuration for the Azimuth CAPI operator
capiOperator:
  # Indicates whether the Azimuth CAPI operator should be enabled
  enabled: true
  chart:
    repo: https://stackhpc.github.io/azimuth-capi-operator
    name: azimuth-capi-operator
    version: 0.1.0-dev.0.feature-argo-support.119
  release:
    name: azimuth-capi-operator
    namespace: azimuth
    defaultsTemplate: |-
      {{- if .Values.zenith.enabled }}
      config:
        zenith:
          registrarAdminUrl: {{ include "azimuth-argo.zenith.registrar.adminUrl" . }}
          {{- with (include "azimuth-argo.zenith.sshd.host" .) }}
          sshdHost: {{ . }}
          {{- end }}
          {{- with (include "azimuth-argo.zenith.sshd.port" .) }}
          sshdPort: {{ . }}
          {{- end }}
      {{- end }}
    values: {}
    valuesTemplate: ""

# Configuration for Azimuth itself
azimuth:
  chart:
    repo: https://stackhpc.github.io/azimuth
    name: azimuth
    version: 0.1.0-dev.0.feature-argo-addons.701
  release:
    name: azimuth
    namespace: azimuth
    defaultsTemplate: |
      tags:
        apps: {{ .Values.zenith.enabled | ternary "true" "false" }}
        clusters: {{ .Values.awx.enabled | ternary "true" "false" }}
        kubernetes: {{ .Values.capiOperator.enabled | ternary "true" "false" }}
      ingress:
        {{- if .Values.ingress.baseDomain }}
        host: {{ printf "%s.%s" .Values.ingress.subdomains.azimuth .Values.ingress.baseDomain }}
        {{- end }}
        annotations: {{- toYaml .Values.ingress.annotations | nindent 6 }}
        tls:
          {{- if .Values.ingress.tls.enabled }}
          enabled: true
          {{- if .Values.wildcardCertificate.enabled }}
          secretName: {{ .Values.wildcardCertificate.secretName }}
          {{- else }}
          annotations: {{- include "azimuth-argo.ingress.tls.annotations" . | nindent 8 -}}
          {{- end }}
          {{- else }}
          enabled: false
          {{- end }}
      authenticators:
        - name: password
          type: openstack-password
          label: Username + Password
          openstackPassword: {}
      {{- if .Values.zenith.enabled }}
      apps:
        {{- if .Values.ingress.baseDomain }}
        baseDomain: {{ .Values.ingress.baseDomain }}
        {{- end }}
        {{- with (include "azimuth-argo.zenith.registrar.externalUrl" .) }}
        registrarExternalUrl: {{ . }}
        {{- end }}
        registrarAdminUrl: {{ include "azimuth-argo.zenith.registrar.adminUrl" . }}
        {{- with (include "azimuth-argo.zenith.sshd.host" .) }}
        sshdHost: {{ . }}
        {{- end }}
        {{- with (include "azimuth-argo.zenith.sshd.port" .) }}
        sshdPort: {{ . }}
        {{- end }}
      {{- end }}
      {{- if .Values.awx.enabled }}
      clusterEngine:
        awx:
          url:
          verifySsl:
          username:
          passwordSecretName:
          createTeams:
          createTeamAllowAllPermission:
          createResources:
          adminUsername:
          adminPasswordSecretName:
          executionEnvironment:
          defaultProjects:
        terraformBackend:
          enabled:
          consul:
            address:
      {{- end }}
    values: {}
    valuesTemplate: ""
