# By default, make an installation called azimuth
fullNameOverride: azimuth

# Configuration for the Argo CD 
argocd:
  # The Argo CD cluster to target
  destination:
    # The URL of the API server
    server: https://kubernetes.default.svc
    # The name of the cluster as known to Argo CD
    # Takes precedence over server if given
    name:
  # The Argo CD project configuration
  project:
    sourceRepos:
      - "*"
    clusterResourceWhitelist:
      - group: "*"
        kind: "*"
    destinations:
      - server: "*"
        namespace: "*"
  # The sync policy to use with Argo apps
  # See https://argo-cd.readthedocs.io/en/stable/user-guide/auto_sync/
  #     https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - "CreateNamespace=true"
  # Configuration for the self-managing Argo CD app
  selfManaged:
    # Indicates whether the Argo CD should be self-managing
    enabled: false
    # The location of the kustomize configuration
    repo: https://github.com/stackhpc/azimuth-argo.git
    path: kustomize/argocd
    version: main
    # Kustomize options for the Argo app
    # See https://argo-cd.readthedocs.io/en/stable/user-guide/kustomize/
    kustomize: {}
    kustomizeTemplate: ""

# Values for the raw chart, used to post templated manifests where no chart is available
rawChart:
  repo: https://charts.helm.sh/incubator
  name: raw
  version: 0.2.5

# Configuration for the wildcard certificate, if used
wildcardCertificate:
  # Indicates if a wildcard certificate should be used
  enabled: false
  # The name of the secret containing the wildcard certificate
  # This will be the same in each namespace in which it is reflected
  secretName: azimuth-tls
  # The namespace to create the "master copy" of the secret in
  secretNamespace: azimuth

# Configuration for ingress
ingress:
  # The base domain for the ingress
  baseDomain:
  # Annotations added to all ingresses in the deployment
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: 16k
  # TLS configuration for the ingress
  tls:
    # Indicates whether TLS should be enabled
    enabled: true
  # The subdomains to use for the various components
  subdomains:
    azimuth: portal
    zenithRegistrar: registrar
    harborCore: registry
    harborNotary: notary
    cloudMetricsGrafana: metrics

# Configuration for cert-manager
certManager:
  # Indicates if cert-manager should be enabled
  # NOTE: cert-manager is a required dependency of Cluster API
  enabled: true
  chart:
    repo: https://charts.jetstack.io
    name: cert-manager
    version: v1.11.0
  release:
    name: cert-manager
    namespace: cert-manager
    values:
      installCRDs: true
    valuesTemplate: ""
  # Configuration for the HTTP-01 issuer that should be used for HTTPS support
  acmeHttp01Issuer:
    enabled: true
    name: letsencrypt
    server: https://acme-v02.api.letsencrypt.org/directory
    ingressClass: nginx

# Configuration for the Cluster API providers
clusterApi:
  # Indicates if the Cluster API controllers should be enabled
  enabled: true
  # Configuration for the core provider
  core:
    repo: https://github.com/stackhpc/azimuth-argo.git
    path: kustomize/cluster-api-core
    version: main
    # Kustomize options for the Argo app
    # See https://argo-cd.readthedocs.io/en/stable/user-guide/kustomize/
    kustomize: {}
    kustomizeTemplate: ""
  # Configuration for the bootstrap provider
  bootstrap:
    repo: https://github.com/stackhpc/azimuth-argo.git
    path: kustomize/cluster-api-bootstrap
    version: main
    # Kustomize options for the Argo app
    # See https://argo-cd.readthedocs.io/en/stable/user-guide/kustomize/
    kustomize: {}
    kustomizeTemplate: ""
  # Configuration for the kubeadm control plane provider
  controlPlane:
    repo: https://github.com/stackhpc/azimuth-argo.git
    path: kustomize/cluster-api-control-plane
    version: main
    # Kustomize options for the Argo app
    # See https://argo-cd.readthedocs.io/en/stable/user-guide/kustomize/
    kustomize: {}
    kustomizeTemplate: ""
  # Configuation for the openstack infratructure provider
  openstack:
    repo: https://github.com/stackhpc/azimuth-argo.git
    path: kustomize/cluster-api-openstack
    version: main
    # Kustomize options for the Argo app
    # See https://argo-cd.readthedocs.io/en/stable/user-guide/kustomize/
    kustomize: {}
    kustomizeTemplate: ""
  # Configuration for the StackHPC addon provider
  addons:
    chart:
      repo: https://stackhpc.github.io/cluster-api-addon-provider
      name: cluster-api-addon-provider
      version: 0.1.0-dev.0.feature-argo-support.31
    release:
      name: cluster-api-addon-provider
      namespace: capi-addon-system
      values: {}
      valuesTemplate: ""

# Configuration for Consul
consul:
  # Indicates if Consul should be enabled
  enabled: true
  chart:
    repo: https://helm.releases.hashicorp.com
    name: consul
    version: 0.49.2
  release:
    name: consul
    namespace: azimuth
    values:
      # Avoid the repeated "consul" in the names by default
      fullnameOverride: consul
    valuesTemplate: ""

# Configuration for Zenith
zenith:
  # Indicates if Zenith should be enabled
  enabled: true
  chart:
    repo: https://stackhpc.github.io/zenith
    name: zenith-server
    version: 0.1.0-dev.0.main.168
  release:
    name: zenith-server
    namespace: azimuth
    defaultsTemplate: |
      common:
        consul:
          address: {{ include "azimuth-argo.consul.host" . | quote }}
        ingress:
          baseDomain: {{ include "azimuth-argo.ingress.baseDomain" . }}
          annotations: {{- toYaml .Values.ingress.annotations | nindent 6 }}
          tls:
            {{- if .Values.ingress.tls.enabled }}
            enabled: true
            {{- if .Values.wildcardCertificate.enabled }}
            secretName: {{ .Values.wildcardCertificate.secretName }}
            {{- else }}
            annotations: {{- include "azimuth-argo.ingress.tls.annotations" . | nindent 8 -}}
            {{- end }}
            {{- else }}
            enabled: false
            {{- end }}
      sync:
        config:
          kubernetes:
            ingress:
              auth:
                url: {{
                  printf
                    "http://%s-api.%s.svc.cluster.local/api/session/verify/"
                    .Values.azimuth.release.name
                    .Values.azimuth.release.namespace
                }}
                signinUrl: {{
                  printf
                    "%s://%s.%s/auth/login"
                    (.Values.ingress.tls.enabled | ternary "https" "http")
                    .Values.ingress.subdomains.azimuth
                    .Values.ingress.baseDomain
                }}
      registrar:
        ingress:
          subdomain: {{ .Values.ingress.subdomains.zenithRegistrar }}
        config:
          reservedSubdomains: {{- values .Values.ingress.subdomains | toYaml | nindent 6 }}
    values:
      # We don't need Zenith to deploy a Consul server
      consul:
        enabled: false
      sync:
        config:
          kubernetes:
            ingress:
              auth:
                nextUrlParam: next
                requestHeaders:
                  accept: application/json
                responseHeaders:
                  - X-Remote-User
    valuesTemplate: ""

# Configuration for the Azimuth CAPI operator
capiOperator:
  # Indicates whether the Azimuth CAPI operator should be enabled
  enabled: true
  chart:
    repo: https://stackhpc.github.io/azimuth-capi-operator
    name: azimuth-capi-operator
    version: 0.1.0-dev.0.feature-argo-support.114
  release:
    name: azimuth-capi-operator
    namespace: azimuth
    defaultsTemplate: |
      zenith:
        registrarAdminUrl: {{ include "azimuth-argo.zenith.registrar.adminUrl" . }}
        sshdService:
          name: {{ include "azimuth-argo.zenith.componentName" (list . "sshd") }}
          namespace: {{ .Values.zenith.release.namespace }}
    values:
      capiHelm:
        defaultValues:
          addons:
            openstack:
              cloudConfig:
                BlockStorage:
                  ignore-volume-az: "true"
              csiCinder:
                storageClass:
                  availabilityZone: nova
    valuesTemplate: ""

# Configuration for Azimuth itself
azimuth:
  chart:
    repo: https://stackhpc.github.io/azimuth
    name: azimuth
    version: 0.1.0-dev.0.main.168
  release:
    name: azimuth
    namespace: azimuth
    values: {}
    valuesTemplate: ""
