apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ include "azimuth-argo.fullName" . }}
  labels: {{ include "azimuth-argo.labels" . | nindent 4 }}
  annotations:
    # Apps will not delete if the project is gone
    helm.sh/resource-policy: keep
    # Make sure that the project exists before everything else when Argo is being used
    argocd.argoproj.io/sync-wave: "-2"
spec: {{ toYaml .Values.argocd.project | nindent 2 }}
