{{- if .Values.argocd.selfManaged.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ list . "argocd" | include "azimuth-argo.componentName" }}
  labels: {{ list . "argocd" | include "azimuth-argo.componentLabels" | nindent 4 }}
  annotations:
    # ArgoCD should be synchronised before everything else
    argocd.argoproj.io/sync-wave: "-1"
  # Don't include the resource finalizer so that the Argo deployment is left behind when the app is deleted
spec:
  destination:
    {{-
      .Values.argocd.selfManaged.release.namespace |
        default .Release.Namespace |
        list . |
        include "azimuth-argo.app.destination" |
        nindent 4
    }}
  project: {{ include "azimuth-argo.fullName" . }}
  source:
    {{- include "azimuth-argo.app.source.helm" (list . .Values.argocd.selfManaged) | nindent 4 }}
  syncPolicy: {{ toYaml .Values.argocd.syncPolicy | nindent 4 }}
{{- end }}
