{{- if .Values.argocd.selfManaged.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ list . "argocd" | include "azimuth-argo.componentName" }}
  labels: {{ list . "argocd" | include "azimuth-argo.componentLabels" | nindent 4 }}
  annotations:
    # ArgoCD should be synchronised before everything else
    argocd.argoproj.io/sync-wave: "-1"
spec:
  destination: {{ list . .Release.Namespace | include "azimuth-argo.app.destination" | nindent 4 }}
  project: {{ include "azimuth-argo.fullName" . }}
  source:
    repoURL: {{ .Values.argocd.selfManaged.repo }}
    path: {{ .Values.argocd.selfManaged.path }}
    targetRevision: {{ .Values.argocd.selfManaged.version }}
    kustomize: {{
      include
        "azimuth-argo.util.merge"
        (list
          .
          .Values.argocd.selfManaged.kustomize
          .Values.argocd.selfManaged.kustomizeTemplate
        ) |
        nindent 6
    }}
  syncPolicy: {{ toYaml .Values.argocd.syncPolicy | nindent 4 }}
{{- end }}
