---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ list . "azimuth" | include "azimuth-argo.componentName" }}
  labels: {{ list . "azimuth" | include "azimuth-argo.componentLabels" | nindent 4 }}
  annotations:
    # Azimuth should deploy after everything else
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    {{-
      list . .Values.azimuth.release.namespace |
        include "azimuth-argo.app.destination" |
        nindent 4
    }}
  project: {{ include "azimuth-argo.fullName" . }}
  source:
    {{- include "azimuth-argo.app.source.helm" (list . .Values.azimuth) | nindent 4 }}
  syncPolicy: {{ toYaml .Values.argocd.syncPolicy | nindent 4 }}
