{{- if .Values.capiOperator.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ list . "capi-operator" | include "azimuth-argo.componentName" }}
  labels: {{ list . "capi-operator" | include "azimuth-argo.componentLabels" | nindent 4 }}
  annotations:
    # The CAPI operator should deploy after Zenith
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    {{-
      list . .Values.capiOperator.release.namespace |
        include "azimuth-argo.app.destination" |
        nindent 4
    }}
  project: {{ include "azimuth-argo.fullName" . }}
  source:
    {{- include "azimuth-argo.app.source.helm" (list . .Values.capiOperator) | nindent 4 }}
  syncPolicy: {{ toYaml .Values.argocd.syncPolicy | nindent 4 }}
{{- end }}
