{{- define "azimuth-argo.cert-manager.issuer.manifests" -}}
- apiVersion: cert-manager.io/v1
  kind: ClusterIssuer
  metadata:
    name: {{ .Values.certManager.acmeHttp01Issuer.name }}
  spec:
    acme:
      server: {{ .Values.certManager.acmeHttp01Issuer.server }}
      privateKeySecretRef:
        name: {{ .Values.certManager.acmeHttp01Issuer.name }}-privkey
      solvers:
        - http01:
            ingress:
              class: {{ .Values.certManager.acmeHttp01Issuer.ingressClass }}
{{- end }}

{{- if .Values.certManager.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ list . "cert-manager" | include "azimuth-argo.componentName" }}
  labels: {{ list . "cert-manager" | include "azimuth-argo.componentLabels" | nindent 4 }}
  annotations:
    # cert-manager has no other dependencies
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    {{-
      list . .Values.certManager.release.namespace |
        include "azimuth-argo.app.destination" |
        nindent 4
    }}
  project: {{ include "azimuth-argo.fullName" . }}
  source: {{ include "azimuth-argo.app.source.helm" (list . .Values.certManager) | nindent 4 }}
  syncPolicy: {{ toYaml .Values.argocd.syncPolicy | nindent 4 }}
{{- if .Values.certManager.acmeHttp01Issuer.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ list . "acme-http01-issuer" | include "azimuth-argo.componentName" }}
  labels: {{ list . "acme-http01-issuer" | include "azimuth-argo.componentLabels" | nindent 4 }}
  annotations:
    # Install the issuer after cert-manager is healthy
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination: {{ list . | include "azimuth-argo.app.destination" | nindent 4 }}
  project: {{ include "azimuth-argo.fullName" . }}
  source: {{
    include
      "azimuth-argo.app.source.manifests"
      (list . .Values.certManager.release.name "azimuth-argo.cert-manager.issuer.manifests") |
    nindent 4
  }}
  syncPolicy: {{ toYaml .Values.argocd.syncPolicy | nindent 4 }}
{{- end }}
{{- end }}
