{{- if .Values.clusterApi.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ list . "capi-core" | include "azimuth-argo.componentName" }}
  labels: {{ list . "capi-core" | include "azimuth-argo.componentLabels" | nindent 4 }}
  annotations:
    # Cluster API components should sync after cert-manager is healthy
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination: {{ list . "capi-system" | include "azimuth-argo.app.destination" | nindent 4 }}
  project: {{ include "azimuth-argo.fullName" . }}
  source: {{ include "azimuth-argo.app.source.kustomize" (list . .Values.clusterApi.core) | nindent 4 }}
  syncPolicy: {{ toYaml .Values.argocd.syncPolicy | nindent 4 }}
  # Ignore differences in the caBundle injected by cert-manager
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/conversion/webhook/clientConfig/caBundle
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ list . "capi-bootstrap" | include "azimuth-argo.componentName" }}
  labels: {{ list . "capi-bootstrap" | include "azimuth-argo.componentLabels" | nindent 4 }}
  annotations:
    # Cluster API components should sync after cert-manager is healthy
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination: {{ list . "capi-kubeadm-bootstrap-system" | include "azimuth-argo.app.destination" | nindent 4 }}
  project: {{ include "azimuth-argo.fullName" . }}
  source: {{ include "azimuth-argo.app.source.kustomize" (list . .Values.clusterApi.bootstrap) | nindent 4 }}
  syncPolicy: {{ toYaml .Values.argocd.syncPolicy | nindent 4 }}
  # Ignore differences in the caBundle injected by cert-manager
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/conversion/webhook/clientConfig/caBundle
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ list . "capi-control-plane" | include "azimuth-argo.componentName" }}
  labels: {{ list . "capi-control-plane" | include "azimuth-argo.componentLabels" | nindent 4 }}
  annotations:
    # Cluster API components should sync after cert-manager is healthy
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination: {{ list . "capi-kubeadm-control-plane-system" | include "azimuth-argo.app.destination" | nindent 4 }}
  project: {{ include "azimuth-argo.fullName" . }}
  source: {{ include "azimuth-argo.app.source.kustomize" (list . .Values.clusterApi.controlPlane) | nindent 4 }}
  syncPolicy: {{ toYaml .Values.argocd.syncPolicy | nindent 4 }}
  # Ignore differences in the caBundle injected by cert-manager
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/conversion/webhook/clientConfig/caBundle
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ list . "capi-openstack" | include "azimuth-argo.componentName" }}
  labels: {{ list . "capi-openstack" | include "azimuth-argo.componentLabels" | nindent 4 }}
  annotations:
    # Cluster API components should sync after cert-manager is healthy
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination: {{ list . "capo-system" | include "azimuth-argo.app.destination" | nindent 4 }}
  project: {{ include "azimuth-argo.fullName" . }}
  source: {{ include "azimuth-argo.app.source.kustomize" (list . .Values.clusterApi.openstack) | nindent 4 }}
  syncPolicy: {{ toYaml .Values.argocd.syncPolicy | nindent 4 }}
  # Ignore differences in the caBundle injected by cert-manager
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/conversion/webhook/clientConfig/caBundle
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ list . "capi-addons" | include "azimuth-argo.componentName" }}
  labels: {{ list . "capi-addons" | include "azimuth-argo.componentLabels" | nindent 4 }}
  annotations:
    # Cluster API components should sync after cert-manager is healthy
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    {{-
      list . .Values.clusterApi.addons.release.namespace |
        include "azimuth-argo.app.destination" |
        nindent 4
    }}
  project: {{ include "azimuth-argo.fullName" . }}
  source: {{ include "azimuth-argo.app.source.helm" (list . .Values.clusterApi.addons) | nindent 4 }}
  syncPolicy: {{ toYaml .Values.argocd.syncPolicy | nindent 4 }}
{{- end }}
