apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/kubernetes-sigs/cluster-api/releases/download/v1.3.3/control-plane-components.yaml

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/args
        value:
          - --leader-elect
          - --metrics-bind-addr=localhost:8080
    target:
      kind: Deployment
