apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# See https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#manage-argo-cd-using-argo-cd

bases:
  - github.com/argoproj/argo-cd//manifests/cluster-install?ref=v2.5.9

# changes to config maps
patchesStrategicMerge:
  - patches/argocd-cm.yaml
