apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/kubernetes-sigs/cluster-api-provider-openstack/releases/download/v0.7.0/infrastructure-components.yaml
